language: ruby
rvm:
- 2.0.0
notifications:
  hipchat:
    rooms:
      secure: MzzVPTNOdoNtXwEdCXufM9QK1iyLI04NRfEXPQ95reprQEZcLGNOqu4W2cU1inFqQAm95mGjHelK2o+kkruDSzmUse00Xr/DwPCs8kpS2tj6Tn6JWXFWPB02mlnW68vTZuo5wKqHFmPXqRzexLgtT63SyUAIJz8cFnpWvZrjqsk=
