language: ruby
rvm:
- 2.0.0
gemfile:
- Gemfile
notifications:
  hipchat:
    rooms:
      secure: Q1pO5hjJVToILfRzEYZBL4TRYcbOdRRFGvBSmSEb5t8pKMb8Wv+PRLATW0BwzgAxc0tcLhQgnpOdxYFVQr28PlrsFQioVi5PkOeRiA9Uk9zot7oPvkMGciRMXgkhYfxCSTIwaqfGcC0agtD9cCjLCN+AaPKi4ZwalBwY4I8bd8I=
